- clothing.json
Check for missing (, "Enabled": true) inserts, check for (possible) translation mishaps, improve some of the translations if needed,
CHANGE REVAN TO RAVEN
> Clothing.json 100% translated

- clothing.json
> Reven -> Raven FIXED Clothing.json

- .gitattributes
- .travis.yml
- checkjson.py
- enemies.json
- objectives.json
Add a Travis config so we can verify the JSONs
And fix issues with some of the json missing "," on a few lines
> Travis Support

- .gitattributes
- area_names.json
- checkjson.py
- npc_names.txt
- opening_scene.json
- skill_descriptions.json
- skills.json
Also, what happen to skill_descriptions.json have 2 Enabled?
> revert revert hack

- misc_items.json
- objectives_do_not_edit.json
> adding more TL's

- enemies.json
[9:39 AM] Kyle873: it's like the way they decided to name enemies was to take potshots at a keyboard with pencils and go "YUP, THIS IS GOOD."
Split into 12 commits in case I fucked something up.
> enemy.json translations

- class_descriptions.json
Let's Make Busters Great Again
> Buster clipping fix 2: Electric Boogaloo

- npc_styles.json
Not too sure if nouns or adjectives are better... so it's not perfect.
> Some npc style translations

- promise_orders.json
> THIS BETTER FUCKING WORK THIS TIME

- menustuff.json
- structures.json
Base customization stuff is also in here too, but I'm not touching it until I get to that point if it's not already done by then.
> More structure stuff

- questnames.json
- story_summary.json
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
> AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

- gen_enemy_mats.py
[12:48 AM] Marrub: hold on before you merge I gotta fix that
DAMN IT KYLE
> Fix generator for real this time

- Active Effects Descriptions.json
I translated all of the effects.
> WACKY EFFECTS

- Effects.json
- Menus.json
I actually feel dirty changing "People" to "ppl"
> Search menu and effects stuff

- Affix Descriptions.json
> translated a few stat descriptions

- Affix Descriptions.json
> TYPOOOOOOOOOOOO

- rmd/Enemies.json
- rmd/Enemy Cores.json
- rmd/Promise Orders.json
- Added more translations to cores
- Added more translations to enemies
- Fixed a Promise Order typo
> More things added

- rmd/Promise Order Objectives.json
- rmd/Promise Orders.json
- rmd/Quest Names.json
- rmd/Quest Objectives.json
- Added more Promise Order translations
- Added more translations to enemies the quest names & quest objectives
> PO's, quest names, E-Trial Objectives

- rmd/Quest Objectives.json
Should have majority of these done now
> Enemy E-Trials updated

- rmd/Promise Orders.json
- rmd/Skill Descriptions.json
Turns out the font is very picky about the punctuation it expects.
> Use the right apostrophe

- rmd/Active Effects Descriptions.json
- rmd/Costumes.json
- rmd/Effects.json
- rmd/Menus.json
Out of all the things that don't resize, none of these do. Fuck my life.
> Effects stuff

- rmd/Menus.json
- rmd/Team Quests.json
Quests are still pretty rough, but it's a start at least
> Fixed OCR errors and search team quests

- rmd/Menus.json
I renamed the current entries back based on the idea that you wouldn't actually know what they are until you've actually done the research to begin with. They also match up more closely with their JP counterparts as well.
> Lab research stuff

- rmd/Enemies.json
- rmd/Search Team Quest Descriptions.json
First test of the tool. Descriptions are all auto-generated based on the methodology described in #299.
> Search team descriptions, first test

- rmd/Story 1.json
Stuff to check out:
664
699
834
> 617-1007 [Search Team Crisis to Fildia's speech]

- rmd/Story 1.json
Reverts Arks-Layer/PSNovaTranslations#337
> Revert "Add files via upload"

- rmd/Story 1.json
With like only ten lines of dialog though. Changed some things around so that it makes sense, and I'll have to revise these later when I have my vita around me.
> SpaceNEET is back

- rmd/Affixes.json
- rmd/Boost Items.json
- rmd/Consumable Items.json
- rmd/Materials.json
- rmd/Skills.json
I need to double-check the affix lines that may be too long due to vertical spacing!
> Re-lining and some edits

- rmd/Effects.json
- rmd/Menus.json
- rmd/Promise Orders.json
- rmd/Skills.json
I hit a lot of the untranslated skill descriptions and re-did a few that were missing numbers. Could use a quick check before merging.
Also, some of the skill names were messed up for some reason so I did those as well.
> Partisan -> Partizan and tons of skill stuff

- rmd/Chargen Parts.json
- rmd/Enemies.json
- rmd/Enemy Cores.json
- rmd/Gigantes.json
- rmd/Materials.json
- rmd/Promise Orders.json
- rmd/Quests.json
- rmd/Search Team.json
> fix inconsistent/wrong enemy names

- rmd/Enemies.json
- rmd/Enemy Cores.json
- rmd/Materials.json
- rmd/Promise Orders.json
- rmd/Quests.json
Translated some materials and redid the names of several enemies. In addition, I had also fixed some OCR errors.
> Fixing OCR errors and renaming enemies

- rmd/Materials.json
- rmd/Weapons.json
Fixed some weird kanji and gave new translations to some weapons that were mixed up.
> Assorted fixes

- rmd/Story 1.json
> Update Story 1.json

- rmd/Communication Messages.json
> Update Communication Messages.json

- rmd/Enemy Cores.json
- rmd/Materials.json
missed this last time apparently
> Fix G-Ga Wonda VH Core

- rmd/Story Summaries.json
corrected previous sentence errors and added few new entries. and also i found out the reason for text cutting. apparently the maximim text length is 128 characters anything after is being cut..
> corrected and added another few entries

- rmd/Loading Screens.json
- rmd/Techniques.json
Fixed a couple small issues I noticed while playing in loading screens and Technique descriptions.
> A couple grammar fixes

- rmd/Story 1.json
gonna upload before typhoon hits, better if i can check it if it's working.
> upload, translated some of Story1

- rmd/Affixes.json
- rmd/Enemy Cores.json
- rmd/Materials.json
- rmd/Promise Orders.json
- rmd/Story 1.json
- rmd/Story 2.json
- rmd/Story 5.json
- rmd/Theater.json
Please check, and i hope there will be a new build, there's something i want to check before continuing with promise orders and quests.
> Additional translations

- rmd/Materials.json
- rmd/Promise Orders.json
- rmd/Quests.json
- rmd/Search Team.json
- rmd/Story 2.json
so I'll just leave it here. going to wait for the Juna/Juno fix... and also I notice that some of the extra hard materials is not on the document and also the dlc dialogs...
> Gonna take a break

- rmd/Food.json
- rmd/Weapons.json
already merged from master to mine before editing the files.
> typo corrections

- rmd/Story 1.json
- rmd/Story 2.json
- rmd/Tutorials.json
> Start of translations of Tutorials
